config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'homes#top'

  resources :diaries do
    resource :favorites, only: [:create, :destroy]
    resources :diary_comments, only: [:create, :destroy]
    resource :bookmarks, only: [:create, :destroy]
  end

  get 'weekly_rank' => 'diaries#weekly_rank', as: 'weekly_rank'

  get 'bookmarks' => 'bookmarks#index', as: 'bookmarks'

  resources :users, only: [:show, :edit, :update, :destroy] do
    member do
      get :unsubscribe
    end
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  resources :records, only: [:create, :index, :edit, :update, :destroy]

  get '/search' => 'search#search'

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :diary
end

app/models/diary.rb
class Diary < ApplicationRecord
  belongs_to :user
  attachment :image
  has_many :diary_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :bookmarks, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def bookmarked_by?(user)
    bookmarks.where(user_id: user.id).exists?
  end

  def self.search_for(content)
    where('caption LIKE ?', '%' + content + '%')
  end

  def self.last_week
    now = Time.current
    joins(:favorites).where(diaries: { created_at: now.prev_week..now.prev_week(:sunday) }).group(:id).order("count(*) desc").limit(3)
  end
  
  with_options presence: true do
    validates :image
    validates :distance
    validates :hour
    validates :minute
    validates :second
    validates :pace_minute
    validates :pace_second
    validates :caption
  end
  
end

app/models/diary_comment.rb
class DiaryComment < ApplicationRecord
  belongs_to :user
  belongs_to :diary

  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :diary
end

app/models/record.rb
class Record < ApplicationRecord
  belongs_to :user
  
  with_options presence: true do
    validates :distance
    validates :hour
    validates :minute
    validates :second
    validates :pace_minute
    validates :pace_second
  end
  
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :diaries, dependent: :destroy
  has_many :diary_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :records, dependent: :destroy
  has_many :bookmarks, dependent: :destroy

  attachment :profile_image

  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  has_many :followings, through: :relationships, source: :followed

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end
  
  def me?(user_id)
    id === user_id
  end

  def self.search_for(content)
    where('name LIKE ?', '%' + content + '%')
  end

  validates :name, length: { maximum: 20, minimum: 2 }, uniqueness: true
  validates :residence, length: { maximum: 20 }
  validates :introduction, length: { maximum: 100 }
  validates :occupation, length: { maximum: 20 }

  def self.guest
    find_or_create_by!(email: 'guest@guest.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲスト"
    end
  end
end

app/controllers/diaries_controller.rb
class DiariesController < ApplicationController
  def new
    @diary = Diary.new
  end

  def create
    @diary = Diary.new(diary_params)
    @diary.user_id = current_user.id
    if @diary.save
      redirect_to diaries_path, notice: "投稿しました。"
    else
      render 'new'
    end
  end

  def index
    @diaries = Diary.page(params[:page]).per(9).reverse_order
  end

  def show
    @diary = Diary.find(params[:id])
    @diary_comment = DiaryComment.new
  end

  def edit
  end

  def update
  end

  def destroy
    @diary = Diary.find(params[:id])
    @diary.destroy
    redirect_to diaries_path
  end

  def weekly_rank
    @ranks = Diary.last_week
  end

  private

  def diary_params
    params.require(:diary).permit(:image, :caption, :distance, :hour, :minute, :second, :pace_minute, :pace_second)
  end

  def self.search_for(content)
    Diary.where('name LIKE ?', '%' + content + '%')
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :ensure_correct_user, only: [:edit, :update, :destroy]

  def index
    @record = Record.new
    @records = Record.where(user_id: current_user.id)
  end

  def create
    @record = Record.new(record_params)
    @record.user_id = current_user.id
    if @record.save
      redirect_to records_path, notice: "記録しました。"
    else
      @records = Record.where(user_id: current_user.id)
      render 'index'
    end
  end

  def edit
    @record = Record.find(params[:id])
  end

  def update
    @record = Record.find(params[:id])
    if @record.update(record_params)
      redirect_to records_path, notice: "更新しました。"
    else
      render 'edit'
    end
  end

  def destroy
    @record = Record.find(params[:id])
    @record.destroy
    redirect_to records_path, alert: "削除しました。"
  end

  private

  def record_params
    params.require(:record).permit(:start_time, :distance, :hour, :minute, :second, :pace_minute, :pace_second)
  end

  def ensure_correct_user
    @record = Record.find(params[:id])
    unless @record.user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  
  def search
    @model = params[:model]
    @content = params[:content]
    @data = if @model == 'user'
              User.search_for(@content)
            else
              Diary.search_for(@content).page(params[:page]).per(9).reverse_order
            end
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:edit, :update, :unsubscribe, :destroy]

  def show
    @user = User.find(params[:id])
    @diaries = @user.diaries.page(params[:page]).per(9).reverse_order
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "更新しました。"
    else
      render 'edit'
    end
  end

  def unsubscribe
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to root_path, notice: "退会処理を受け付けました。"
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction, :residence, :occupation)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user.me? current_user.id
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/diaries_helper.rb
module DiariesHelper
end

app/helpers/diary_comments_helper.rb
module DiaryCommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/diaries/_index.html.erb
<div class="row">
  <% diaries.each do |diary| %>
    <div class="d-flex flex-wrap">

      <div id="diary_<%= diary.id %>" class="card m-3" style="width: 300px; height: 480px;">
        <%= link_to diary_path(diary.id) do %>
        <%= attachment_image_tag diary, :image, :fill, 300, 200 %>
        <% end %>

        <div class="card-body">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              距離　　　<%= diary.distance %> km<br>
              時間　　　<%= sprintf("%02d", diary.hour) %> : <%= sprintf("%02d", diary.minute) %> : <%= sprintf("%02d", diary.second) %><br>
              ペース　　<%= sprintf("%02d", diary.pace_minute) %>' <%= sprintf("%02d", diary.pace_second) %>" / km
            </li>
          </ul>

          <p class="d-inline-block text-truncate" style="max-width: 250px;"><%= diary.caption %></p>
          <p>
            <%= link_to user_path(diary.user) do %>
            <%= attachment_image_tag diary.user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", size: '50x50', class: "mt-3 rounded-circle"; %>
            <% end %>
          </p>
          <div class="d-flex justify-content-between">
            <div class="favorite-btn">
              <%= render "favorites/favorite-btn", diary: diary %>
            </div>
            
            <div>
              <%= diary.diary_comments.count %>コメント
            </div>
            
            <div class="bookmark-btn">
              <%= render "bookmarks/bookmark-btn", diary: diary %>
            </div>
            
            <div>
              <%= link_to "詳細", diary_path(diary.id), class: "text-dark"; %>
            </div>
          </div>

        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/diaries/index.html.erb
<div class="container" style="width: 1000px;">

  <!--検索ボックス-->
    <%= render "search/search-box" %>

  <!--投稿一覧-->
  <h2 class="row justify-content-center border-bottom">新着</h2>
    <%= render "diaries/index", diaries: @diaries %>
  
  <div class="row justify-content-center my-5">
    <%= paginate @diaries %>
  </div>

</div>

app/views/diaries/new.html.erb
<div class="container">
  <%= render 'layouts/errors', obj: @diary %>
  <div class="row justify-content-center my-4">
    <h2>ダイアリー投稿フォーム</h2>
  </div>

  <div class="row justify-content-center">
    <%= form_with model: @diary, local:true do |f| %>

    <div class="form-group row">
      <h5 class="col-md-3">画像</h5>
      <div class="col-md-7">
        <%= f.attachment_field :image %>
      </div>
    </div>

    <div class="form-group row">
      <h5 class="col-md-3">距離</h5>
      <div class="col-md-7">
        <%= f.text_field :distance, size: 7, placeholder: '5.0' %> km
      </div>
    </div>

    <div class="form-group row">
      <h5 class="col-md-3">時間</h5>
      <div class="col-md-7">
        <%= f.text_field :hour, size: 7, placeholder: '00' %> : <%= f.text_field :minute, size: 7, placeholder: '30' %> : <%= f.text_field :second, size: 7, placeholder: '00' %>
      </div>
    </div>

    <div class="form-group row">
      <h5 class="col-md-3">ペース</h5>
      <div class="col-md-7">
        <%= f.text_field :pace_minute, size: 7, placeholder: '06' %> ' <%= f.text_field :pace_second, size: 7, placeholder: '00' %> " / km
      </div>
    </div>

    <div class="form-group row">
      <div class="col-md-12">
        <%= f.text_area :caption, size: "80x7", placeholder: '思い出を書いてみよう！' %>
      </div>
    </div>

    <div class="row">
      <%= f.submit '投稿', class: "btn btn-dark btn-lg btn-block" %>
    </div>

    <% end %>
　</div>

</div>

app/views/diaries/show.html.erb
<div class="container" style="width: 70%;">
  <div class="row justify-content-center">

    <!--投稿詳細-->
    <div id="diary_<%= @diary.id %>" class="card m-3" style="width: 100%; height: 100%;">
      <%= attachment_image_tag @diary, :image %>
      <div class="card-body">

        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            距離　　　<%= @diary.distance %> km<br>
            時間　　　<%= sprintf("%02d", @diary.hour) %> : <%= sprintf("%02d", @diary.minute) %> : <%= sprintf("%02d", @diary.second) %><br>
            ペース　　<%= sprintf("%02d", @diary.pace_minute) %>' <%= sprintf("%02d", @diary.pace_second) %>" / km
          </li>
        </ul><hr>

          <p>
            <%= @diary.caption %>
          </p>
          <p>
            <%= link_to user_path(@diary.user) do %>
            <%= attachment_image_tag @diary.user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", size: "50x50", class:"mt-3 rounded-circle"; %>
            <% end %>
          </p>
          <p><%= @diary.user.name %></p>
          <p class="favorite-btn">
            <%= render "favorites/favorite-btn", diary: @diary %>
          </p>
          <p class="comments-count">
            <%= @diary.diary_comments.count %>コメント
          </p>
          <p class="bookmark-btn">
            <%= render "bookmarks/bookmark-btn", diary: @diary %>
          </p>
          <p>投稿日時：<%= @diary.created_at.strftime('%Y/%m/%d') %></p>
          <% if @diary.user == current_user %>
            <%= link_to "削除", diary_path(@diary), method: :delete, class: "btn btn-danger" %>
          <% end %>
          <hr>

          <!--コメントエリア-->
          <div class="diary_comments">

            <div class="comments_index card-text">
              <%= render "diary_comments/index", diary: @diary %>
            </div>
            <hr>

            <!--コメント入力フォーム-->
             <div class="new-comment card-text">
               <%= form_with(model:[@diary, @diary_comment]) do |f| %>
               <div class="form-group">
                 <label for="exampleFormControlTextarea1">コメントする</label>
                 <%= f.text_area :comment, rows:'5', class: "form-control",placeholder: "コメントを書いてみよう！" %>
               </div>
              <%= f.submit "送信する", class:"btn btn-lg btn-dark mt-2 float-right" %>
              <% end %>
             </div>

          </div>
      </div>

    </div>
  </div>
</div>

app/views/diaries/weekly_rank.html.erb
<div class="container mt-5" style="width: 1000px;">

  <h2 class="row justify-content-center border-bottom">
    週間 good<i class="far fa-thumbs-up", style="color: green;"></i>数ランキング TOP3
  </h2>
  <h6>
    ※ 先週の投稿の中でgood数の多かった3件を表示しています。
  </h6>
  
  <%= render "diaries/index", diaries: @ranks %>

</div>

app/views/records/edit.html.erb
<div class="container">
  <%= render 'layouts/errors', obj: @record %>

  <div class="row justify-content-center my-4">
    <h3>記録編集</h3>
  </div>

  <div class="row justify-content-center">
    <%= form_with model: @record, local:true do |f| %>
    <h5>ランニング日時</h5>
    <%= f.datetime_select :start_time %>
    <h5 class="mt-3">距離</h5>
    <%= f.text_field :distance, size: 7, placeholder: '5.0' %> km
    <h5 class="mt-3">時間</h5>
    <%= f.text_field :hour, size: 7, placeholder: '00' %> : <%= f.text_field :minute, size: 7, placeholder: '30' %> : <%= f.text_field :second, size: 7, placeholder: '00' %>
    <h5 class="mt-3">ペース</h5>
    <%= f.text_field :pace_minute, size: 7, placeholder: '06' %> ' <%= f.text_field :pace_second, size: 7, placeholder: '00' %> " / km
    <div class="d-flex justify-content-around mt-4">
      <%= f.submit "更新", class: "btn btn-sm btn-dark" %>
      <%= link_to "削除", record_path(@record), method: :delete, class: "btn btn-sm btn-danger"; %>
    </div>
    <div class="mt-4">
      <%= link_to "戻る", records_path, class: "far fa-arrow-alt-circle-left nav-link text-dark"; %>
    </div>
    <% end %>
  </div>

</div>

app/views/records/index.html.erb
<div class="container">
  <%= render 'layouts/errors', obj: @record %>
  <div class="row mt-4">
    <div class="col-md-4">

      <%= form_with model: @record, local:true do |f| %>
      <h5 class="mt-3">ランニング日時</h5>
      <%= f.datetime_select :start_time %>
      <h5 class="mt-3">距離</h5>
      <%= f.text_field :distance, size: 7, placeholder: '5.0' %> km
      <h5 class="mt-3">時間</h5>
      <%= f.text_field :hour, size: 7, placeholder: '00' %> : <%= f.text_field :minute, size: 7, placeholder: '30' %> : <%= f.text_field :second, size: 7, placeholder: '00' %>
      <h5 class="mt-3">ペース</h5>
      <%= f.text_field :pace_minute, size: 7, placeholder: '06' %> ' <%= f.text_field :pace_second, size: 7, placeholder: '00' %> " / km
      <%= f.submit '記録', class: "btn btn-dark btn-sm btn-block mt-3" %>
      <% end %>

    </div>

    <div class="col-md-7 col-md-offset-1">

      <%= month_calendar events: @records do |date, records| %>
      <%= date.day %>
      <% records.each do |record| %>
      <%= link_to record.start_time.strftime("%H:%M"), edit_record_path(record) %>
      <%= record.distance %>km
      <%= sprintf("%02d", record.hour) %>:<%= sprintf("%02d", record.minute) %>:<%= sprintf("%02d", record.second) %>
      <%= sprintf("%02d", record.pace_minute) %>'<%= sprintf("%02d", record.pace_second) %>"/km
      <% end %>
      <% end %>

    </div>

  </div>
</div>