config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'homes#top'

  resources :diaries do
    resource :favorites, only: [:create, :destroy]
    resources :diary_comments, only: [:create, :destroy]
    resource :bookmarks, only: [:create, :destroy]
  end

  get 'weekly_rank' => 'diaries#weekly_rank', as: 'weekly_rank'

  get 'bookmarks' => 'bookmarks#index', as: 'bookmarks'

  resources :users, only: [:show, :edit, :update, :destroy] do
    member do
      get :unsubscribe
    end
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  resources :records, only: [:create, :index, :edit, :update, :destroy]

  get '/search' => 'search#search'

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :diary
end

app/models/diary.rb
class Diary < ApplicationRecord
  belongs_to :user
  attachment :image
  has_many :diary_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :bookmarks, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def bookmarked_by?(user)
    bookmarks.where(user_id: user.id).exists?
  end

  def self.search_for(content)
    where('caption LIKE ?', '%' + content + '%')
  end

  def self.last_week
    now = Time.current
    joins(:favorites).where(diaries: { created_at: now.prev_week..now.prev_week(:sunday) }).group(:id).order("count(*) desc").limit(3)
  end
  
  with_options presence: true do
    validates :image
    validates :distance
    validates :hour
    validates :minute
    validates :second
    validates :pace_minute
    validates :pace_second
    validates :caption
  end
  
end

app/models/diary_comment.rb
class DiaryComment < ApplicationRecord
  belongs_to :user
  belongs_to :diary

  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :diary
end

app/models/record.rb
class Record < ApplicationRecord
  belongs_to :user
  
  with_options presence: true do
    validates :distance
    validates :hour
    validates :minute
    validates :second
    validates :pace_minute
    validates :pace_second
  end
  
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :diaries, dependent: :destroy
  has_many :diary_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :records, dependent: :destroy
  has_many :bookmarks, dependent: :destroy

  attachment :profile_image

  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  has_many :followings, through: :relationships, source: :followed

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end
  
  def me?(user_id)
    id === user_id
  end

  def self.search_for(content)
    where('name LIKE ?', '%' + content + '%')
  end

  validates :name, length: { maximum: 20, minimum: 2 }, uniqueness: true
  validates :residence, length: { maximum: 20 }
  validates :introduction, length: { maximum: 100 }
  validates :occupation, length: { maximum: 20 }

  def self.guest
    find_or_create_by!(email: 'guest@guest.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲスト"
    end
  end
end

app/controllers/diaries_controller.rb
class DiariesController < ApplicationController
  def new
    @diary = Diary.new
  end

  def create
    @diary = Diary.new(diary_params)
    @diary.user_id = current_user.id
    if @diary.save
      redirect_to diaries_path, notice: "投稿しました。"
    else
      render 'new'
    end
  end

  def index
    @diaries = Diary.page(params[:page]).per(9).reverse_order
  end

  def show
    @diary = Diary.find(params[:id])
    @diary_comment = DiaryComment.new
  end

  def edit
  end

  def update
  end

  def destroy
    @diary = Diary.find(params[:id])
    @diary.destroy
    redirect_to diaries_path
  end

  def weekly_rank
    @ranks = Diary.last_week
  end

  private

  def diary_params
    params.require(:diary).permit(:image, :caption, :distance, :hour, :minute, :second, :pace_minute, :pace_second)
  end

  def self.search_for(content)
    Diary.where('name LIKE ?', '%' + content + '%')
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :ensure_correct_user, only: [:edit, :update, :destroy]

  def index
    @record = Record.new
    @records = Record.where(user_id: current_user.id)
  end

  def create
    @record = Record.new(record_params)
    @record.user_id = current_user.id
    if @record.save
      redirect_to records_path, notice: "記録しました。"
    else
      @records = Record.where(user_id: current_user.id)
      render 'index'
    end
  end

  def edit
    @record = Record.find(params[:id])
  end

  def update
    @record = Record.find(params[:id])
    if @record.update(record_params)
      redirect_to records_path, notice: "更新しました。"
    else
      render 'edit'
    end
  end

  def destroy
    @record = Record.find(params[:id])
    @record.destroy
    redirect_to records_path, alert: "削除しました。"
  end

  private

  def record_params
    params.require(:record).permit(:start_time, :distance, :hour, :minute, :second, :pace_minute, :pace_second)
  end

  def ensure_correct_user
    @record = Record.find(params[:id])
    unless @record.user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  
  def search
    @model = params[:model]
    @content = params[:content]
    @data = if @model == 'user'
              User.search_for(@content)
            else
              Diary.search_for(@content).page(params[:page]).per(9).reverse_order
            end
  end
  
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to diaries_path, notice: 'ゲストユーザーとしてログインしました。'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:edit, :update, :unsubscribe, :destroy]

  def show
    @user = User.find(params[:id])
    @diaries = @user.diaries.page(params[:page]).per(9).reverse_order
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "更新しました。"
    else
      render 'edit'
    end
  end

  def unsubscribe
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to root_path, notice: "退会処理を受け付けました。"
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction, :residence, :occupation)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user.me? current_user.id
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/diaries_helper.rb
module DiariesHelper
end

app/helpers/diary_comments_helper.rb
module DiaryCommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class="table border-bottom">
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td>
          <%= link_to user_path(user) do %>
          <%= attachment_image_tag user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", size: "50x50", class: "rounded-circle"; %>
          <% end %>
        </td>
        <td><%= user.name %></td>
        <td>フォロー数：<%= user.followings.count %></td>
        <td>フォロワー数：<%= user.followers.count %></td>
        <% if !user.me?(current_user.id) %>
        <% if current_user.following?(user) %>
        <td><%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete, class: "btn btn-dark" %></td>
        <% else %>
        <td><%= link_to "フォローする", user_relationships_path(user.id), method: :POST, class: "btn btn-outline-dark" %></td>
        <% end %>
        <% else %><td colspan="1"></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/edit.html.erb
<div class="container">
  <%= render 'layouts/errors', obj: @user %>
  <div class="row justify-content-center my-4">
    <h2>プロフィール編集</h2>
  </div>

  <div class="row justify-content-center">
    <%= form_with model:@user, local:true do |f| %>

    <div class="form-group row justify-content-center">
    <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg", class:"rounded-circle"; %>
    </div>

    <div class="form-group row">
      <div class="col-md-5"></div>
      <div class="col-md-7" >
        <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
      </div>
    </div>

    <div class="form-group row">
      <h5 class="col-md-5">名前</h5>
      <div class="col-md-7">
        <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%>
      </div>
    </div>

    <div class="form-group row">
      <h5 class="col-md-5">居住地</h5>
      <div class="col-md-7">
        <%= f.text_field :residence, autofocus: true, id:"inputName", placeholder:"居住地は20文字以内です。"%>
      </div>
    </div>

    <div class="form-group row">
      <h5 class="col-md-5">職業</h5>
      <div class="col-md-7">
        <%= f.text_field :occupation, autofocus: true, id:"inputName", placeholder:"職業は20文字以内です。"%>
      </div>
    </div>

    <div class="form-group row">
      <h5 class="col-md-5">自己紹介</h5>
      <div class="col-md-7">
        <%= f.text_area :introduction, size: "50x4", autofocus: true, id:"inputName", placeholder:"自己紹介は100文字以内です。"%>
      </div>
    </div>

    <div class="d-flex justify-content-around mt-4">
      <%= link_to "戻る", user_path(@user), class: "far fa-arrow-alt-circle-left nav-link text-dark"; %>
      <%= f.submit '変更を保存', class: "btn btn-dark btn-sm text-right" %>
    </div>

    <% end %>
　</div>

　<div class="row justify-content-end">
　  <%= link_to '退会', unsubscribe_user_path(@user), class: "btn btn-danger btn-sm"; %>
　</div>

</div>

app/views/users/show.html.erb
<div class="container" style="width: 1000px;">
  <div class="row justify-content-center my-4">
    <h2>プロフィール</h2>
  </div>

  <div class="row justify-content-center">
    <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg", size: "100x100", class:"rounded-circle"; %>
  </div>

  <h4 class="row justify-content-center">
    <%= @user.name %>
  </h4>

<div class="profile-container mt-4">
  <p><i class="fas fa-map-marker-alt"></i>   <%= @user.residence %></p>
  <p><i class="fas fa-briefcase"></i>   <%= @user.occupation %></p>
  <p><%= @user.introduction %></p>
  <table>
    <tr>
      <th>フォロー</th>
      <th><%= link_to @user.followings.count, user_followings_path(@user) %></th>
    </tr>
    <tr>
      <th>フォロワー</th>
      <th><%= link_to @user.followers.count, user_followers_path(@user) %></th>
    </tr>
  </table>

  <% if !@user.me?(current_user.id) %>
    <% if current_user.following?(@user) %>
      <%= link_to "フォロー外す", user_relationships_path(@user.id), method: :delete, class: "btn btn-dark"; %>
    <% else %>
      <%= link_to "フォローする", user_relationships_path(@user.id), method: :post, class: "btn btn-outline-dark"; %>
    <% end %>
  <% else %>
    <%= link_to " ブックマーク一覧", bookmarks_path, class: "far fa-bookmark"; %><br>
    <%= link_to " プロフィール編集",edit_user_path(@user), class: "far fa-edit"; %>
  <% end %>
</div>
<hr>


  <!--投稿一覧-->
  <h2 class="row justify-content-center"><%= @user.name%>さんの投稿</h2>
  <hr>

    <%= render "diaries/index", diaries: @diaries %>

<div class="row justify-content-center my-5">
  <%= paginate @diaries %>
</div>

</div>

app/views/users/unsubscribe.html.erb
<div class="text-center" style="margin-top: 100px;">

  <p class="font-weight-bold">
    本当に退会しますか？
  </p>
  <p>
    退会すると、プロフィールやこれまでの記録、投稿が閲覧できなくなります。<br>
    退会する場合は、「退会する」をクリックしてください。
  </p>

  <%= link_to '退会しない', edit_user_path(@user), class: "btn btn-sm btn-primary mr-5" %>
  <%= link_to '退会する', user_path(@user), method: :delete, class: "btn btn-sm btn-danger" %>

</div>